language: python
python:
  - "3.6"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r RULEngine/requirements.txt
# command to run tests
script: nosetests
notifications:
    slack:
        on_success: change
        on_failure: always
        rooms:
            - robocupulaval:TyyFRQ6Tpv49h1bmIlXJNfxu#team-ia-github
